[package]
name = "copc-rs"
version = "0.3.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2021"

description = "Cloud Optimized Point Cloud (COPC) reader."
homepage = "https://github.com/pka/copc-rs"
repository = "https://github.com/pka/copc-rs"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["lidar", "pointcloud", "copc", "las", "geo"]
categories = ["science::geo", "rendering::data-formats"]
exclude = [
    "tests/data",    
]

[dependencies]
byteorder = "1.4.3"
las = "0.9.2"
laz = "0.8.3"